[scalarField]
name = "scalarFieldName"
engine = "NATIVE_SERIAL"
fieldType = "Normal"
spaceCompo = 1
timeCompo = 1
fedofName = "space"

[scalarField.space]
feType = "Scalar"
basisContinuity = "H1"
basisInterpolation = "Lagrange"
ipType = "Equidistance"
basisType = "Monomial"
alpha = 0.0
beta = 0.0
lambda = 0.5
islocal = true
order = 1
quadOptName = "quadOpt"

# @QuadratureOpt
[scalarField.space.quadOpt]
isHomogeneous = true
quadratureType = "GaussLegendre"
order = 2
# nips = 3
# nsd = 2
# topoType = "Line"
# alpha = 0.0
# beta = 0.0
# lambda = 0.5
