[material]
name = "nameOfMaterial"
propNames = ["prop1", "prop2", "prop3"]

[material.prop1]
# This is same as the UserFunction.toml
name = "prop1"
returnType = "Scalar" # For scalar properties
#          = "Vector" # For vector properties
#          = "Matrix" # For matrix properties

numReturns = 1 # number of returns, it is 1 for scalar

argType = "Space"
#       = "Time" # property is a function of time
#       = "SpaceTime" # property is a function of space and time
#       = "Constant" # property is a constant value

numArgs = 3 # number of arguments

luaScript = "./hello.lua" # lua script

luaFunctionName = "hello" #lua function

value = 1.0 # constant scalar value
#     = [1.0, 2.0, 3.0] # constant vector value
#     = [[1.0, 2.0, 3.0],
#        [4.0, 5.0, 6.0],
#        [7.0, 8.0, 9.0],] # constant matrix value

[material.prop2]
name = "prop2"
returnType = "Vector" # For scalar properties
numReturns = 2
argType = "Constant"
value = [1.0, 2.0, 3.0] # constant vector value
